RES 011 skeleton of the admin panel
Coderscamp-2021-2022-Lukasz-Kamil/Project2.React.Restaurant pull request #14
Opened 2022-02-03 00:36 UTC by DonataB

2022-02-07 17:32 UTC, kam237zasada requested changes

2022-02-07 17:32 UTC, kam237zasada commented on src/components/AdminPage/AdminNavigation/AdminMenuPages.js
> +};
please create separate file for Pages Component and use { source, name, icon, key } instead of just props in line 7

2022-02-08 19:39 UTC, kam237zasada approved these changes

2022-02-08 19:40 UTC, kam237zasada commented
Looks fine, only one thing to improve in next step -> mobile view:
![Przechwytywanie](https://user-images.githubusercontent.com/57039178/153062965-d4a1db33-6732-4363-97b9-0aaac205c04b.JPG)

2022-02-08 19:41 UTC, lagdush approved these changes

2022-02-08 19:44 UTC, merged