RES-015-delete-user-modal
Coderscamp-2021-2022-Lukasz-Kamil/Project2.React.Restaurant pull request #16
Opened 2022-02-05 11:51 UTC by EMEZYK

2022-02-06 12:41 UTC, lagdush requested changes
Do you know about this error?
<img width="514" alt="Zrzut ekranu 2022-02-6 o 13 38 32" src="https://user-images.githubusercontent.com/38866668/152681207-ce4ae979-48dd-4855-94e4-c41e290d9a1f.png">


Delete unused variables and comments. Modal looks nice.

2022-02-06 12:41 UTC, lagdush commented on src/components/Modal/Cart.js
> +        <span>Are you sure you want to permanently remove this item?</span>
Are you sure you want to permanently remove this user?

2022-02-06 17:45 UTC, EMEZYK commented
Yes, but I have already fix this error.

2022-02-07 14:38 UTC, lagdush submitted a review, later dismissed

2022-02-07 14:49 UTC, lagdush approved these changes

2022-02-07 15:46 UTC, DonataB approved these changes

2022-02-07 15:46 UTC, merged