RES-006-contact-page
Coderscamp-2021-2022-Lukasz-Kamil/Project2.React.Restaurant pull request #8
Opened 2022-01-21 17:24 UTC by EMEZYK

2022-01-22 10:35 UTC, RafalPe submitted a review, later dismissed
Seems fine

2022-01-22 13:22 UTC, lagdush requested changes
<img width="726" alt="Zrzut ekranu 2022-01-22 o 14 14 37" src="https://user-images.githubusercontent.com/38866668/150640156-1dc90ffc-4693-4989-b1d5-70d133e32d6a.png">
Work on the layout and responsiveness.

2022-01-22 13:22 UTC, lagdush commented on public/index.html
> +    />
this should be in one import from google fonts.

2022-01-22 13:22 UTC, lagdush commented on src/components/ContactPage/ContactPage.js
> +            <img
Where is alt?

2022-01-24 17:19 UTC, lagdush requested changes
<img width="666" alt="Zrzut ekranu 2022-01-24 o 18 18 36" src="https://user-images.githubusercontent.com/38866668/150832263-4615e51b-6de6-4a08-8243-d758b7274696.png">
Still needs improvement

2022-01-24 21:12 UTC, lagdush requested changes
<img width="420" alt="Zrzut ekranu 2022-01-24 o 22 10 04" src="https://user-images.githubusercontent.com/38866668/150865508-8ac55e77-2231-40bc-a581-408bae0c99f3.png">
<img width="639" alt="Zrzut ekranu 2022-01-24 o 22 10 12" src="https://user-images.githubusercontent.com/38866668/150865517-3454d3f1-bd57-4f08-bd59-68bc8cb002bf.png">
There is still room for improvement.

2022-01-30 14:05 UTC, lagdush approved these changes

2022-01-30 16:18 UTC, MateuszWyborski approved these changes
Looking good

2022-01-30 16:19 UTC, merged