RES-007-component-with-navigation
Coderscamp-2021-2022-Lukasz-Kamil/Project2.React.Restaurant pull request #9
Opened 2022-01-21 21:46 UTC by RafalPe

Add a navigation bar for customers

2022-01-21 22:51 UTC, lagdush requested changes

2022-01-21 22:51 UTC, lagdush commented on src/components/NavigationBar/NavigationBar.js
> +                    </Nav.Link>
You can make a separate component from it and give it props.

2022-01-21 22:51 UTC, lagdush commented on src/components/NavigationBar/NavigationBar.js
> +                        </NavLink>
You can make a separate component from it and give it props.

2022-01-22 09:26 UTC, lagdush commented on src/components/NavigationBar/NavigationBar.js
> +                        <NavLink exact to='/contact' className="text-decoration-none text-white" activeClassName="active">
See what errors you get in the inspector and please fix them.
<img width="1389" alt="Zrzut ekranu 2022-01-22 o 10 19 53" src="https://user-images.githubusercontent.com/38866668/150632954-2b820992-6353-4a77-af0d-7f75e36189e2.png">

2022-01-22 17:17 UTC, lagdush requested changes

2022-01-22 17:17 UTC, lagdush commented on src/components/ContactPage/ContactPage.js
> +      <NavigationBar />
Everything looks cool and we can almost merge it. You still have to handle the navigation nicely. It's not good to add a navigation component to every view. Try to fix it. If you can't make it by tomorrow, talk to me.

2022-01-22 17:24 UTC, lagdush commented on src/components/NavigationBar/NavigationBar.js
> +                    />
you can map something like this

2022-01-23 15:48 UTC, lagdush requested changes
One last small change and it will be ok.

2022-01-23 15:48 UTC, lagdush commented on src/components/NavigationBar/Pages.js
> +    ];
You don't use these props anywhere, so you can remove them.

2022-01-23 15:48 UTC, lagdush commented on src/components/NavigationBar/PagesOnMobile.js
> +        {source: "/contact", icon: ContactIcon}
You don't use these props anywhere, so you can remove them.

2022-01-23 17:01 UTC, lagdush approved these changes
Well done.

2022-01-23 20:59 UTC, EMEZYK approved these changes

2022-01-23 21:25 UTC, merged